### ISSUE TITLE
full_splits.py: restart chapter behaves differently for City

### ISSUE THREAD

**Issue by thomas-daniels** [rhelmot/CelesteMagicTimer#23]
Steps to reproduce:

* Run full_splits.py with a route for a chapter (I've attached my own `city.route` and `site.route` that split by subchapters, created using make_segment_splits.py, I don't think there's a big difference between them)
* Go through the chapter far enough that at least the first split is finished.
* Restart chapter.

Expected behavior:

* Splits reset.

Actual behavior:

* For at least Site and Ridge (didn't test this out with other chapters so far), the splits do reset nicely, so like this:
![1630252717_1758_29082021_702x112](https://user-images.githubusercontent.com/8034604/131257034-f1cc2c2f-1d52-44db-b81e-f3162d76b2b7.png)

* For City, they don't. The autosplitter does recognize that the chapter time has gone to zero again, but it still thinks I'm in the middle of a run so it looks like this:
![1630252448_1754_29082021_730x104](https://user-images.githubusercontent.com/8034604/131256879-9b41f209-14f6-4a5d-945a-41602ad7fa0d.png)

[Archive of my routes with city.route and site.route](https://github.com/rhelmot/CelesteMagicTimer/files/7072813/routes.tar.gz)

**Comment by rhelmot** [comment]
This is actually a bug with make_segment_splits.py. I've fixed it in the linked commit, but if you want to fix your existing route files you'll need to go in with the python shell and change the restart trigger the same way the commit changes it.

**Comment by thomas-daniels** [comment]
That made it work, thanks!
